### ISSUE TITLE
Fatal error:

### ISSUE THREAD

**Issue by faelhs** [ianrodriguesbr/cielo-api#1]
Estou enfrentando este problema ao tentar executar um checkout basico de teste.

Fatal error: Uncaught exception 'Ramsey\Uuid\Exception\UnsatisfiedDependencyException' with message 'When calling Ramsey\Uuid\Converter\Time\DegradedTimeConverter::calculateTime on a 32-bit system, Moontoast\Math\BigNumber must be present.' in C:\AppServ\www\a\vendor\ramsey\uuid\src\Converter\Time\DegradedTimeConverter.php:37 Stack trace: #0 C:\AppServ\www\a\vendor\ramsey\uuid\src\Generator\DefaultTimeGenerator.php(88): Ramsey\Uuid\Converter\Time\DegradedTimeConverter->calculateTime(1481287374, 851887) #1 C:\AppServ\www\a\vendor\ramsey\uuid\src\UuidFactory.php(204): Ramsey\Uuid\Generator\DefaultTimeGenerator->generate(NULL, NULL) #2 C:\AppServ\www\a\vendor\ramsey\uuid\src\Uuid.php(651): Ramsey\Uuid\UuidFactory->uuid1(NULL, NULL) #3 C:\AppServ\www\a\vendor\ianrodriguesbr\cielo-api\src\CieloClient.php(30): Ramsey\Uuid\Uuid::uuid1() #4 C:\AppServ\www\a\vendor\ianrodriguesbr\cielo-api\src\Cielo.php(30): IanRodriguesBR\Cielo\CieloClient->__construct(true) #5 C:\AppServ\www\a\a.php(12): IanRodriguesBR\Cielo\Cielo->__construct(' in C:\AppServ\www\a\vendor\ramsey\uuid\src\Converter\Time\DegradedTimeConverter.php on line 37

**Comment by ianrodriguesbr** [comment]
Corrigido! Esse problema só acontece em máquinas 32bits.

**Comment by faelhs** [comment]
Minha maquina de testes é 64 bits, pode ser alguma configuração no apache
ou php?


2016-12-09 18:32 GMT-02:00 Ian Rodrigues <notifications@github.com>:
